#!/bin/bash
# Definition des alias raccourcis
alias cdt='cd ~/test/'

# Definition des alias de compilation
alias gccf="gcc -Wall -Wextra -Werror"
alias g++f="g++ -Wall -Wextra -Werror"

# Definition des alias
alias clean="find . -name '*~' -execdir rm {} \;"
alias modsh="vim $C_PATH_TO_PERSONNAL_CONFIG/zshrc"
alias purgevim="rf -f ~/.vim/tmp/*.swp ~/.vim/tmp/.*.swp"
alias rl="source ~/.zshrc"

# School only aliases
if [[ `uname` = "Darwin" ]]; then
	# misc
	alias auteur="echo '$USER' > auteur"
	alias libft="cp -r $LIB .; rm -rf libft/.git"
	alias next="source nextprev next"
	alias op=ocamlopt
	alias prev="source nextprev prev"

	# cd alias
	alias cdc='cd ~/Rendu'
	alias cdl='cd $LIB'
	alias cds='cd ~/scripts/'
	alias goinfre='cd /nfs/sgoinfre/goinfre/'

	# compil alias
	alias gccl="gcc -I $LIB/includes -L $LIB -lft"
	alias gcclf="gcc -Wall -Wextra -Werror -I $LIB/includes -L $LIB -lft"
fi
